apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redhat-ods-applications

resources:
- dscinitialization.yaml
- datasciencecluster.yaml
- postgres.yaml
- etcd.yaml
- etcd-networkpolicy.yaml
- milvus.yaml
- llamastackdistribution.yaml
- networkpolicy.yaml
- route.yaml
